[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/news"
  status = 200

[functions]
  node_bundler = "esbuild"
